# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           '/:categories/:year/:month/:day/:title'
#relative_permalinks: true

# Setup
title:               Nishant Sharma
tagline:             'Wisdom on TECH '
description:         'Tech Blogs on tools, techniques and devices I use'
url:                 http://blog.nishantsharma.xyz
baseurl:             ''
paginate:            5
future:              true

# About/contact
author:
  name:              Nishant Sharma
  url:               http://nishantsharma.xyz
  email:             nishant.shharma@gmail.com

github:
  repo:              https://github.com/nishantshharma/nishantshharma.github.io

# Pages
pages:
  Home: '/'
  About: '/about'
  Tags: '/tags'

# Localization Strings
str_continue_reading: "Continue reading..."

# Custom vars
version:             1.0.0

# Gems
plugins: [jekyll-paginate]
